etude/urls.py
from django.urls import path
from .views import select_personne, saverepetpajsm, savepajsm, creerdossierpajsm, accord_intervenant, \
    inscription_intervenant, suite_accord, saveenquete, bilan_sondage, bilan_etude, prepare_csv, ffait_csv, \
    fait_entete_pajinter_R, fait_entete_pajsaisie_R, ffait_csv_pajsaisie, prepare_csv_pajsaisie,questions_pdf, \
    fait_entete_spss
from django.contrib.auth.views import LoginView


urlpatterns = [
    path('login/', LoginView.as_view(), name='login', kwargs={'redirect_authenticated_user': True}),
    # pour dossiers
    path('pajfile', select_personne, name='SelectPersonne'),
    path('<str:cissid>', inscription_intervenant, name='inscription'),
    path('saverepetpajsm/<int:qid>/<int:pid>/<int:accid>/', saverepetpajsm, name='saverepetpajsm'),
    path('savepajsm/<int:qid>/<int:pid>/<int:accid>/', savepajsm, name='savepajsm'),
    path('newpajsm/', creerdossierpajsm, name='creerdossierpajsm'),
    # pour enquete
    #path('enquetepaj/', inscription_intervenant, name='inscription_intervenant'),
    path('enquetepaj/<str:iid>', accord_intervenant, name='accord_intervenant'),
    path('accord/<str:iid>', suite_accord, name='suite_accord'),
    path('saveenquetepaj/<str:cid>/<int:qid>', saveenquete, name='saveenquete'),
    path('bilan/', bilan_sondage, name='bilan_sondage'),
    path('bilan2/', bilan_etude, name='bilan_etude'),
    path('csv/<int:questionnaire>/<int:tous>/', prepare_csv, name='prepare_csv'),
    path('csvpaj/<int:paj>/<int:questionnaire>/<int:tous>/<int:seuil>', prepare_csv_pajsaisie, name='prepare_csv_pajsaisie'),
    path('csv/<int:questionnaire>/<int:iteration>/<int:seuil>/<int:tous>/', ffait_csv, name='do_csv'),
    path('enteteR/<int:questionnaire>/', fait_entete_pajinter_R, name='fait_entete_pajinter_R'),
    path('enteteRS/<int:questionnaire>/', fait_entete_pajsaisie_R, name='fait_entete_pajsaisie_R'),
    path('csvpaj/<int:paj>/<int:questionnaire>/<int:iteration>/<int:seuil>/<int:tous>/', ffait_csv_pajsaisie,name='ffait_csv_pajsaisie'),
    path('pdf/<int:questionnaire>/', questions_pdf, name='questions_pdf'),
    path('enteteSPSS_S/<int:questionnaire>/', fait_entete_spss, name='fait_entete_spss'),

]

pajsm/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView
#from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.static import serve
from django.views.generic.base import RedirectView


admin.site.site_header = settings.ADMIN_SITE_HEADER

admin.autodiscover()

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('login/', LoginView.as_view(), name='login', kwargs={'redirect_authenticated_user': True}),
    path('PAJSM/', include('etude.urls')),
    path('', include('accueil.urls')),
   #  path('tsmnew/', include('tsmnew.urls')),
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    path('favicon.ico', RedirectView.as_view(url='/static/imgage/favicon.ico', permanent=True)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

etude/models.py
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models

DEFAULT_UID = 1
# met tous les utilisateurs par defaut a 1 (maliadmin)

## Table des CISSS et CIUSSS (enquete)
class Centresante(models.Model):
    nom = models.CharField(max_length=250, verbose_name="Nom du CISSS ou CIUSSS",)
    lien = models.CharField(max_length=250, verbose_name="Url du commissaire aux plaintes CISSS ou CIUSSS", blank=True, null=True)
    logo = models.ImageField(upload_to='Logos', verbose_name="Logo format png", help_text="PAS D'ACCENT DANS LES NOMS DE FICHIERS", null=True, blank=True)
    courriel = models.CharField(max_length=250, verbose_name="Courriel commissaire aux plaintes")
    tel1 = models.CharField(max_length=250, verbose_name="Tel1 commissaire aux plaintes")
    tel2 = models.CharField(max_length=250, verbose_name="Autre tel du commissaire aux plaintes", blank=True, null=True)

    def __str__(self):
        return '%s' % self.nom


## Table des repondants (intervenants, professionnels etc) (enquete)
### order = ordre des questionnaires (aléatoire), vignettes associées au répondant (aléatoires)
class Intervenant(models.Model):
    code = models.CharField(max_length=50, unique=True, verbose_name="Lien : https://pajsmmj.ntp-ptn.org/PAJSM/enquetepaj/")
    courriel = models.CharField(max_length=250)
    completed = models.IntegerField(default=0)
    concented = models.IntegerField(default=0, verbose_name="Consent = 1, Refuse = 2")
    tirage = models.IntegerField(default=0)
    utilisationsecondaire = models.IntegerField(default=0)
    contactfutur = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    ordre = models.IntegerField(default=0, verbose_name="ordre 1= I, II, III etc; ordre 2= I, V, II etc")
    vignette1 = models.IntegerField(default=0)
    vignette2 = models.IntegerField(default=0)
    date_consentement = models.DateTimeField(blank=True, null=True)
    partie1 = models.IntegerField(default=0, verbose_name="Partie I terminée")
    partie2 = models.IntegerField(default=0, verbose_name="Partie II terminée")
    partie3 = models.IntegerField(default=0, verbose_name="Partie III terminée")
    partie4 = models.IntegerField(default=0, verbose_name="Partie IV terminée")
    partie5 = models.IntegerField(default=0, verbose_name="Partie V terminée")
    partie6 = models.IntegerField(default=0, verbose_name="Partie VI terminée")
    implique = models.IntegerField(default=0)
    connait = models.IntegerField(default=0)
    avocat = models.IntegerField(default=0)
    centresante = models.ForeignKey(Centresante, on_delete=models.DO_NOTHING)

    class Meta:
        unique_together = (('code', 'courriel',),)
        indexes = [models.Index(fields=['code', 'courriel'])]

    def __str__(self):
        return '%s' % self.code


## listes de valeurs typequestion_id=13 (Paj-sm)
class Pajsmlist(models.Model):
    reponse_en = models.CharField(max_length=200,)
    reponse_fr = models.CharField(max_length=200,)

    def __str__(self):
        return '%s' % self.reponse_en


## Table des participants aux PAJSM (étude)
class Personne(models.Model):
    code = models.CharField(max_length=200,)
    selectedpaj = models.ForeignKey(Pajsmlist, default=100, on_delete=models.DO_NOTHING)
    date_indexh = models.DateField(blank=True, null=True)
    completed = models.IntegerField(default=0)
    genre = models.CharField(max_length=200, blank=True, null=True)
    assistant = models.ForeignKey(User, default=DEFAULT_UID, on_delete=models.DO_NOTHING)
    sed = models.TextField(blank=True, null=True)
    nam = models.TextField(blank=True, null=True)
    sddob = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['selectedpaj', 'code']

    def __str__(self):
        return '%s' % self.code


## Definit la forme html des questions ainsi que le type de réponse attendu (texte, bool, date etc)
class Typequestion(models.Model):
    nom = models.CharField(max_length=200, )
    tatable = models.CharField(max_length=200, blank=True, null=True)
    taille = models.CharField(max_length=200, )

    def __str__(self):
        return '%s' % self.nom


##   listes valeurs non dependantes des provinces SANS province
class Listevaleur(models.Model):
    reponse_valeur = models.CharField(max_length=200)
    reponse_en = models.CharField(max_length=200, )
    reponse_fr = models.CharField(max_length=200, )
    typequestion = models.ForeignKey(Typequestion, on_delete=models.DO_NOTHING)

    class Meta:
        ordering = ['typequestion', 'reponse_valeur']

    def __str__(self):
        return '%s' % self.reponse_en


class Victime(models.Model):
    #  listes de valeurs typequestion_id=14 (VICTIME)
    #  Restee a part a cause de la logique du tri des items
    reponse_valeur = models.CharField(max_length=200)
    reponse_en = models.CharField(max_length=200, )
    reponse_fr = models.CharField(max_length=200, )

    class Meta:
        ordering = ['id']

    def __str__(self):
        return '%s' % self.reponse_en


## Accompagnement = suivi par le PAJ_SM (un peut comme verdict ou hearing dans NTP) (étude)
class Accompagnement(models.Model):
    reponse_valeur = models.CharField(max_length=200)
    reponse_en = models.CharField(max_length=200, )
    reponse_fr = models.CharField(max_length=200, )

    class Meta:
        ordering = ['id']

    def __str__(self):
        return '%s' % self.reponse_en


class Questionnaire(models.Model):
    nom_en = models.CharField(max_length=200, )
    nom_fr = models.CharField(max_length=200, )
    description = models.CharField(max_length=200, )
    consigneen = models.TextField(blank=True, null=True,)
    consignefr = models.TextField(blank=True, null=True,)

    def __str__(self):
        return '%s' % self.nom_en


#######################
## Questions utilisees pour tous les questionnaires
# Parent_ID permet de lier l'affichage conditionnel d'une question en fonction de la réponse précédente
# à la question dont l'ID=Parent_id via la relation établie par  le champ relation et la valeur cible prédéfinie
# (par exemple question 2 s'ouvrira si question 1 (parent_id) a comme réponse 998 (cible) avec relation égale)
DEFAULT_PARENT_ID = 1


class Questionpajsm(models.Model):
    questionno = models.IntegerField()
    questionen = models.TextField()
    questionfr = models.TextField(blank=True, null=True)
    questionnaire = models.ForeignKey(Questionnaire, on_delete=models.DO_NOTHING)
    typequestion = models.ForeignKey(Typequestion, on_delete=models.DO_NOTHING)
    parent = models.ForeignKey("self", default=DEFAULT_PARENT_ID, on_delete=models.DO_NOTHING)
    relation = models.CharField(blank=True, null=True, max_length=45,)
    cible = models.CharField(blank=True, null=True, max_length=45,)
    varname = models.CharField(blank=True, null=True, max_length=45,)
    aidefr = models.TextField(blank=True, null=True)
    aideen = models.TextField(blank=True, null=True)
    qstyle = models.CharField(blank=True, null=True, max_length=45,)
    parentvarname = models.CharField(blank=True, null=True, max_length=45,)
    section = models.IntegerField(blank=True, null=True)

    class Meta:
        ordering = ['questionno']

    def __str__(self):
        return '%s' % self.questionen


#######################
## listes de valeurs des questions de typequestion_id=4 (CATEGORIAL)
# Pour les questions qui aparaissent rarement et dont les réponses sont des listes de valeur
class Reponsepajsm(models.Model):
    question = models.ForeignKey(Questionpajsm, on_delete=models.DO_NOTHING)
    reponse_no = models.CharField(max_length=200)
    reponse_valeur = models.CharField(max_length=200)
    reponse_en = models.CharField(max_length=200,)
    reponse_fr = models.CharField(max_length=200,)
    questionnaire = models.ForeignKey(Questionnaire, on_delete=models.DO_NOTHING)
    varname = models.CharField(blank=True, null=True, max_length=45,)

    class Meta:
        ordering = ['reponse_valeur']

    def __str__(self):
        return '%s' % self.reponse_en


#######################
## Enregistrement des reponses des donnees NON repetitives (étude)
class Resultatpajsm(models.Model):
    personne = models.ForeignKey(Personne, on_delete=models.CASCADE)
    question = models.ForeignKey(Questionpajsm, on_delete=models.CASCADE)
    assistant = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    reponsetexte = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    accompagnement = models.ForeignKey(Accompagnement, on_delete=models.DO_NOTHING, default=1)

    class Meta:
        # constraints = [models.UniqueConstraint(fields=['personne', 'assistant', 'question'], name='unique_result')]
        # unique_together = (('personne', 'assistant', 'question', 'accompagnement'),)
        # indexes = [models.Index(fields=['personne', 'assistant', 'question', 'accompagnement'])]
        # constraints = [models.UniqueConstraint(fields=['personne', 'question'], name='unique_result')]
        unique_together = (('personne', 'question', 'accompagnement'),)
        indexes = [models.Index(fields=['personne', 'question', 'accompagnement'])]

    def __str__(self):
        return '%s' % self.reponsetexte


#######################
## Enregistrement des reponses des donnees REPETITIVES (étude)
# Garder le questionnaire_id pour pouvoir effacer une fiche au complet sans faire une requete compliquée
DEFAULT_DATE = '0000-00-00'


class Resultatrepetpajsm(models.Model):
    personne = models.ForeignKey(Personne, on_delete=models.CASCADE)
    assistant = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    questionnaire = models.ForeignKey(Questionnaire, db_index=True, on_delete=models.DO_NOTHING)

etude/forms.py
from django import forms
from pajsm.etude.models import Intervenant


class IntervenantForm(forms.ModelForm):
    class Meta:
        model = Intervenant
        fields = ['courriel',]
        exclude = ()

etude/templates/bilan.html
{% load i18n %}
{% load static %}
<html>
   <head>
        <title>PAJ_SM Enquête</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static 'etude/w3.css' %}">
        <link rel="stylesheet" href="{% static 'etude/sondageM.css' %}">
        <link rel="stylesheet" href="{% static 'etude/w3-theme-maison.css' %}">
        <link rel="stylesheet" href="{% static 'etude/theme-enquete.css' %}">
</head>
<body>
<div class="w3-container">
    <header class="w3-row w3-theme-d3"  id="myHeader">
        <div class="w3-center">
        <h4>Étude sur les Programmes d’accompagnement en justice et santé mentale du Québec</h4>
        </div>
    </header>
  <div class="w3-container w3-sand">
    {% if messages %}
        {% for msg in messages %}
            <div class="alert alert-{{msg.level_tag}}" role="alert">
            {{msg.message}}
            </div>
        {% endfor %}
    {% endif %}
      <a href="{% url 'logout' %}" class="w3-button w3-theme-action"> Logout</a>
      <h4>Bilan Enquête auprès des intervenants PAJ_SM</h4>
       <table class="w3-table-all">
        <tr><th>Origine</th><th>Inscrits</th><th>Consentent</th><th>Refusent</th><th>Ordre des</th><th>Complets</th>
            <th>Avocat</th><th colspan="6">Sections du questionnaire terminées</th>
        </tr>
        <tr><th></th><th></th><th></th><th></th><th>questionnaires 1/2</th><th></th>
            <th></th><th class="w3-theme-l1">P-I</th><th>P-II</th><th>P-III</th><th class="w3-theme-l1">P-IV</th><th class="w3-theme-l1">P-V</th><th>P-VI</th>
        </tr>
        <tr class="w3-theme-l4">
        <td><b>Sommes</b><td> </td><td> </td><td> </td><td> </td><td>{{sommes.SCp}}</td><td> </td>
            <td>{{sommes.Sp1}}</td>
            <td>{{sommes.Sp2}}</td><td>{{sommes.Sp3}}</td><td>{{sommes.Sp4}}</td><td>{{sommes.Sp5}}</td><td>{{sommes.Sp6}}</td>
        </tr>
           {% for ligne in complets %}
        <tr>
        <td>{{ligne.0}}</td><td>{{ligne.4}}</td><td>{{ligne.2}}</td><td>{{ligne.5}}</td><td>{{ligne.6}} / {{ligne.7}}</td><td>{{ligne.1}}</td>
            <td>{{ligne.3}}</td>
            <td>{{ligne.8}}</td><td>{{ligne.9}}</td><td>{{ligne.10}}</td><td>{{ligne.11}}</td><td>{{ligne.12}}</td><td>{{ligne.13}}</td>
        </tr>
        {% endfor %}
        </table>
<h3>To export data</h3>
    <form method="post" action="">
       {% csrf_token %}
           <table class="w3-table-all">
                <tr><td>Questionnaire</td>
                    <td><select name="questionnaireid" >
                    <option value="">Choose the questionnaire to export</option>
                    {% for questionnaire in questionnaires %}
                        {% if questionnaire.id > 100 and questionnaire.id < 10000 %}
                            <option value="{{questionnaire.id}}">{{ questionnaire.nom_en}}</option>
                        {% endif %}
                    {% endfor %}
                    </select>
                    </td>
                </tr>
           <tr><td>Extraire tous les dossiers? (complets ou non)</td><td><input type="checkbox" id="tous" name="tous" value="1"><label for="tous"> Oui tous</label></td></tr>
           <tr><td></td><td><button type="submit" class="placeboutons" name="Exporterdata">Export data only</button></td></tr>
           <tr><td></td><td><button type="submit" class="placeboutons" name="fait_entete_pajinter_R">Export R syntax</button></td></tr>
         </table>
   </form>
</div>
</div>
</body>
</html>

etude/templates/datehospit_snippet.html
{% load formulairesrepet %}
{% autoescape off %}
{% fait_dateh persid=pid ordre=x questionnaire=qid accompagnement=accid %}
{% endautoescape %}

etude/templates/saveenquete.html
{% extends 'enquete_base.html' %}
{% load i18n %}
{% load static %}
{% load formulairespajsm %}

<h2> {{ intervenant.courriel }} - {{ questionnaire }} </h2>

{% block content_fr %}
<form action="" method="post">
{% csrf_token %}
   <input name="iid" type="hidden" value="{{ intervenant.id }}" />
   <input name="qid" type="hidden" value="{{ qid }}" />
{% for num in range %}
<div class="tab ">
    <br />
     <div class="w3-theme-light w3-large">
  <div class="w3-container w3-theme-d1" style="width:{{nbfait|floatformat:0}}%">{{nbfait|floatformat:0}} %
  </div>
</div><br />
{% if num == 1  and questionnaire.consignefr != "" %}
<h4>Consignes</h4>{{ questionnaire.consignefr}}

{% endif %}
    {% if  num == 1 and qid == 104 %}
    <h4><u>Lisez attentivement la vignette suivante</u> :
     {{vignette1.description_txt_fr}}</h4>
    {% elif   num == 5 and qid == 104 %}
    <h4><u>Lisez attentivement la vignette suivante</u> :
    {{vignette2.description_txt_fr}}</h4>
    {% endif %}
    <table class="w3-table-all">
    {% for question in questions %}
        {% if question.section == num %}
            {% if question.typequestion.nom == 'COMMENT' and question.id not in ascendancesF %}
                <tr><td style="text-align: center;"><h4>{{ question.questionfr }}</h4>{{ question.aidefr|default:"" }}</td></tr>
            {% else %}
                {% if question.id not in ascendancesF and question.id not in ascendancesM %}
                    <tr>
                        {% include "enquete_snippet.html" with typequest=question.typequestion textequest=question.questionfr questid=question.id varname=question.varname aide=question.aidefr langue=LANGUAGE_CODE %}
                    </tr>
                {% elif question.id in ascendancesF and question.id in ascendancesM %}
                         {% for enfant in question.questionpajsm_set.all %}
                            {% if forloop.counter == 1 %}
                                <tr style="display: none;" class="child-row-{{question.parent_id}}{{question.relation}}{{question.cible}}">
                                    {% include "enquete_snippet.html" with typequest=question.typequestion textequest=question.questionfr questid=question.id relation=enfant.relation cible=enfant.cible classe="fillemere" varname=question.varname  aide=question.aidefr langue=LANGUAGE_CODE %}
                                </tr>
                            {% endif %}
                         {% endfor %}
                {% elif question.id in ascendancesM and question.id not in ascendancesF %}
                    <tr class="mere">
                        {% for enfant in question.questionpajsm_set.all %}
                            {% if forloop.counter == 1 %}
                                {% include "enquete_snippet.html" with typequest=question.typequestion textequest=question.questionfr questid=question.id relation=enfant.relation cible=enfant.cible classe="mere" varname=question.varname  aide=question.aidefr langue=LANGUAGE_CODE %}
                    </tr>
                            {% endif %}
                         {% endfor %}
                {% endif %}
                {% for enfant in question.questionpajsm_set.all %}
                    {% if enfant.id not in ascendancesM %}
                         <tr style="display: none;" class="child-row-{{enfant.parent_id}}{{enfant.relation}}{{enfant.cible}}">
                             {% include "enquete_snippet.html" with typequest=enfant.typequestion textequest=enfant.questionfr questid=enfant.id classe="fille" varname=enfant.varname  aide=enfant.aidefr langue=LANGUAGE_CODE %}
                         </tr>
                     {% endif %}
                {% endfor %}
            {% endif %}
        {% endif %}
    {% endfor %}
</table>
 {% if num == range|length %}
        <div style="overflow:auto;">
            <div style="float:right;">
                <button type="button" id="prevBtn" onclick="nextPrev(-1)">Précédent</button>
                <button type="submit" name="suite" id="nextBtn" onclick="nextPrev(1)">Enregistrer et Section suivante</button>
            </div>
        </div>
    {% else %}
      <div style="overflow:auto;">
            <div style="float:right;">
                <button type="button" id="prevBtn" onclick="nextPrev(-1)">Précédent</button>
                <button type="button" id="nextBtn" onclick="nextPrev(1)">Suivant</button>
            </div>
      </div>
 {% endif %}
</div>
{% endfor %}

<div style="text-align:center;margin-top:40px;">
{% for num in range %}
  <span class="step"></span>
{% endfor %}
</div>
</form>
{% endblock content_fr %}

etude/templates/savepajsm.html
{% extends 'dossier_base.html' %}
{% load i18n %}
{% load static %}
{% load formulairespajsm %}

{% block content %}
        {% if qid == 5 %}
<h2> {{ code }}--{{hospcode}} - {{ questionnaire }} </h2>
    {% else %}
<h2> {{ code }}--{{hospcode}} - {{ questionnaire }} -- {{ accompagnement.reponse_en }}</h2>
    {% endif %}
{% csrf_token %}
   <input name="pid" type="hidden" value="{{ pid }}" />
   <input name="qid" type="hidden" value="{{ qid }}" />
   <input name="accid" type="hidden" value="{{ accid }}" />
   <div class="tabber">

    {% for question in questions %}
        {% if question.typequestion.nom == 'TITLE' %}
            {% if forloop.counter > 1 %}
                </table></div>
            {% endif %}
                 <div class="tabbertab"><h3>{{ question.questionen|slice:"0:15" }}</h3><b>{{ question.questionen}}</b>
                 <table><tr><td></td><td></td><td></td></tr>
        {% elif question.typequestion.nom == 'COMMENT' %}
            <tr><td class="plusdeux" colspan="3">{{ question.questionen }}<td></tr>
        {% else %}
            {% if question.id not in ascendancesF and question.id not in ascendancesM %}
                <tr class="{% cycle 'Q1' 'Q2' %}">
                    {% include "champs_snippet.html" with typequest=question.typequestion textequest=question.questionen questid=question.id varname=question.varname accompagnement=accid %}
                    {% include "aide_snippet.html" with aide=question.aideen  classe="" %}
                </tr>
            {% elif question.id in ascendancesF and question.id in ascendancesM %}
                     {% for enfant in question.questionpajsm_set.all %}
                        {% if forloop.counter == 1 %}
                            <tr style="display: none;" class="child-row-{{question.parent_id}}{{question.relation}}{{question.cible}}">
                                {% include "champs_snippet.html" with typequest=question.typequestion textequest=question.questionen questid=question.id relation=enfant.relation cible=enfant.cible classe="fillemere" varname=question.varname accompagnement=accid  %}
                                {% include "aide_snippet.html" with aide=question.aideen classe="fillemere" %}
                            </tr>
                        {% endif %}
                     {% endfor %}
            {% elif question.id in ascendancesM and question.id not in ascendancesF %}
                <tr class="mere">
                    {% for enfant in question.questionpajsm_set.all %}
                        {% if forloop.counter == 1 %}
                            {% include "champs_snippet.html" with typequest=question.typequestion textequest=question.questionen questid=question.id relation=enfant.relation cible=enfant.cible classe="mere" varname=question.varname accompagnement=accompagnement.id %}
                            {% include "aide_snippet.html" with aide=question.aideen %}
                </tr>
                        {% endif %}
                     {% endfor %}
            {% endif %}
            {% for enfant in question.questionpajsm_set.all %}
                {% if enfant.id not in ascendancesM %}
                     <tr style="display: none;" class="child-row-{{enfant.parent_id}}{{enfant.relation}}{{enfant.cible}}">
                     {% if enfant.id|divisibleby:2 %}
                         {% include "champs_snippet.html" with typequest=enfant.typequestion textequest=enfant.questionen questid=enfant.id classe="fifille" varname=enfant.varname accompagnement=accid %}
                         {% include "aide_snippet.html" with aide=enfant.aideen classe="fifille" %}
                    {% else %}
                         {% include "champs_snippet.html" with typequest=enfant.typequestion textequest=enfant.questionen questid=enfant.id classe="fille" varname=enfant.varname accompagnement=accid %}
                         {% include "aide_snippet.html" with aide=enfant.aideen classe="fille" %}
                    {% endif %}
                     </tr>
                 {% endif %}
            {% endfor %}
        {% endif %}
    {% endfor %}
</table>
</div>
{% if qid < 10 and qid != 5 %}
<div class="tabbertab"><h3>AUDIENCES</h3><b>Pour rentrer les informations des audiences</b>
    <p>Pour chaque audience en lien avec cette accusation / accompagnement vous devez completer une fiche</p>
    <p>Liste des audiences rentrées pour cette accusation / accompagnement</p>
    <ul>
        {% for fiche in fiches %}
            <li>{% include "datehospit_snippet.html" with x=fiche qid=10 accompagnement=accid %}</li>
        {% endfor %}
    </ul>
      <table><tr><td>Pour creer la premiere fiche d'audience ou accéder aux audiences déjà rentrées :</td>
          <td><a href="{% url 'saverepetpajsm'  10 pid accid %}" class="w3-button w3-theme-action">Nouvelle audience</a></td></tr>
      </table>


</div>
<div class="tabbertab"><h3>DÉLITS</h3><b>Pour rentrer les informations à propos des délits</b>
    <p>Pour chaque délit en lien avec cette accusation / accompagnement vous devez completer une fiche</p>
      <table><tr><td>Pour creer la premiere fiche de délit ou accéder aux délits déjà rentrés :</td>
          <td><a href="{% url 'saverepetpajsm'  11 pid accid %}" class="w3-button w3-theme-action">Nouveau délit</a></td></tr>
      </table>
    {% endif %}
</div><!--Fermeture de la boite à onglets-->
{% endblock content %}